# Generated by Django 3.2 on 2021-04-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210429_1736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tbl_category',
        ),
    ]
